### ISSUE TITLE
get_obsolete_replaced_by_term failing

### ISSUE THREAD

**Issue by dosumis** [INCATools/ubergraph#108]
http://grlc.io/api/INCAtools/ubergraph/sparql/#/default/get_obsolete_replaced_by_term

with parameter http://purl.obolibrary.org/obo/CL_0000044

=> 

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/112839/207178284-4ea6eb8c-ffba-49ab-958c-b402f996f564.png">

grlc rewrite of query looks very odd (why not use <> around IRI.  Does ^^class:IRI usually work?

**Comment by anitacaron** [comment]
The variable's name should have only one word. Now it's working as expected.
