### ISSUE TITLE
CI script is failing because of new RO pipeline

### ISSUE THREAD

**Issue by anitacaron** [INCATools/ubergraph#119]
Error in the GH Action:
```
make: *** No rule to make target 'other_import.owl'.  Stop.
```

Since the RO was updated to use ODK, the `other_imports.owl` was moved to be an import in the ODK way. It was moved to `imports/other_imports.owl`.

As part of the change of RO using ODK, `imports/other_imports.owl` only now have two external classes; all other content was moved to their specific imports.

Is adding this file to the pipeline still necessary?

**Comment by matentzn** [comment]
Should we redirect the PURL to this file?

Question Anita asked still stands.
