### ISSUE TITLE
cardiac muscle cell (sensu Arthopoda) unsatisfiability

### ISSUE THREAD

**Issue by balhoff** [INCATools/ubergraph#123]
The Ubergraph unsatisfiability check reported a new problem. @gouttegd @bvarner-ebi does this look like anything that recently changed in CL?

## [cardiac muscle cell (sensu Arthopoda)](http://purl.obolibrary.org/obo/CL_0000193) SubClassOf [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [cardiac muscle cell (sensu Arthopoda)](http://purl.obolibrary.org/obo/CL_0000193) EquivalentTo [cardiac muscle cell](http://purl.obolibrary.org/obo/CL_0000746) and ([develops from](http://purl.obolibrary.org/obo/RO_0002202) some [cardioblast (sensu Arthropoda)](http://purl.obolibrary.org/obo/CL_0000465))
    - [cardiac muscle cell](http://purl.obolibrary.org/obo/CL_0000746) SubClassOf [develops from](http://purl.obolibrary.org/obo/RO_0002202) some [cardiac muscle myoblast](http://purl.obolibrary.org/obo/CL_0000513)
      - [cardiac muscle myoblast](http://purl.obolibrary.org/obo/CL_0000513) EquivalentTo [myoblast](http://purl.obolibrary.org/obo/CL_0000056) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [cardiac muscle tissue](http://purl.obolibrary.org/obo/UBERON_0001133)) and ([develops into](http://purl.obolibrary.org/obo/RO_0002203) some [cardiac muscle cell](http://purl.obolibrary.org/obo/CL_0000746))
        - [cardiac muscle tissue](http://purl.obolibrary.org/obo/UBERON_0001133) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [heart](http://purl.obolibrary.org/obo/UBERON_0000948)
          - [heart](http://purl.obolibrary.org/obo/UBERON_0000948) SubClassOf [only in taxon](http://purl.obolibrary.org/obo/RO_0002160) some [Vertebrata <vertebrates>](http://purl.obolibrary.org/obo/NCBITaxon_7742)
            - [Vertebrata <vertebrates>](http://purl.obolibrary.org/obo/NCBITaxon_7742) SubClassOf [Craniata <chordates>](http://purl.obolibrary.org/obo/NCBITaxon_89593)
              - [Craniata <chordates>](http://purl.obolibrary.org/obo/NCBITaxon_89593) SubClassOf [Chordata](http://purl.obolibrary.org/obo/NCBITaxon_7711)
                - [Chordata](http://purl.obolibrary.org/obo/NCBITaxon_7711) SubClassOf [Deuterostomia](http://purl.obolibrary.org/obo/NCBITaxon_33511)
            - [only in taxon](http://purl.obolibrary.org/obo/RO_0002160) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
        - [part of](http://purl.obolibrary.org/obo/BFO_0000050) SubPropertyOf: [overlaps](http://purl.obolibrary.org/obo/RO_0002131)
    - [develops from](http://purl.obolibrary.org/obo/RO_0002202) SubPropertyOf: [has developmental contribution from](http://purl.obolibrary.org/obo/RO_0002254)
    - [cardioblast (sensu Arthropoda)](http://purl.obolibrary.org/obo/CL_0000465) SubClassOf [only in taxon](http://purl.obolibrary.org/obo/RO_0002160) some [Arthropoda](http://purl.obolibrary.org/obo/NCBITaxon_6656)
      - [Arthropoda](http://purl.obolibrary.org/obo/NCBITaxon_6656) SubClassOf [Panarthropoda](http://purl.obolibrary.org/obo/NCBITaxon_88770)
        - [Panarthropoda](http://purl.obolibrary.org/obo/NCBITaxon_88770) SubClassOf [Ecdysozoa](http://purl.obolibrary.org/obo/NCBITaxon_1206794)
          - [Ecdysozoa](http://purl.obolibrary.org/obo/NCBITaxon_1206794) SubClassOf [Protostomia](http://purl.obolibrary.org/obo/NCBITaxon_33317)
  - [overlaps](http://purl.obolibrary.org/obo/RO_0002131) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
  - [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Protostomia](http://purl.obolibrary.org/obo/NCBITaxon_33317) DisjointWith [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Deuterostomia](http://purl.obolibrary.org/obo/NCBITaxon_33511)
  - [has developmental contribution from](http://purl.obolibrary.org/obo/RO_0002254) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)

# Axiom Impact 
## Axioms used 1 times
- [cardiac muscle cell (sensu Arthopoda)](http://purl.obolibrary.org/obo/CL_0000193) EquivalentTo [cardiac muscle cell](http://purl.obolibrary.org/obo/CL_0000746) and ([develops from](http://purl.obolibrary.org/obo/RO_0002202) some [cardioblast (sensu Arthropoda)](http://purl.obolibrary.org/obo/CL_0000465)) [cl-base.owl]
- [cardiac muscle myoblast](http://purl.obolibrary.org/obo/CL_0000513) EquivalentTo [myoblast](http://purl.obolibrary.org/obo/CL_0000056) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [cardiac muscle tissue](http://purl.obolibrary.org/obo/UBERON_0001133)) and ([develops into](http://purl.obolibrary.org/obo/RO_0002203) some [cardiac muscle cell](http://purl.obolibrary.org/obo/CL_0000746)) [cl-base.owl]
- [cardioblast (sensu Arthropoda)](http://purl.obolibrary.org/obo/CL_0000465) SubClassOf [only in taxon](http://purl.obolibrary.org/obo/RO_0002160) some [Arthropoda](http://purl.obolibrary.org/obo/NCBITaxon_6656) [cl-base.owl]
- [cardiac muscle cell](http://purl.obolibrary.org/obo/CL_0000746) SubClassOf [develops from](http://purl.obolibrary.org/obo/RO_0002202) some [cardiac muscle myoblast](http://purl.obolibrary.org/obo/CL_0000513) [cl-base.owl]
- [Ecdysozoa](http://purl.obolibrary.org/obo/NCBITaxon_1206794) SubClassOf [Protostomia](http://purl.obolibrary.org/obo/NCBITaxon_33317) [taxslim.owl]
- [Arthropoda](http://purl.obolibrary.org/obo/NCBITaxon_6656) SubClassOf [Panarthropoda](http://purl.obolibrary.org/obo/NCBITaxon_88770) [taxslim.owl]
- [Chordata](http://purl.obolibrary.org/obo/NCBITaxon_7711) SubClassOf [Deuterostomia](http://purl.obolibrary.org/obo/NCBITaxon_33511) [taxslim.owl]
- [Vertebrata <vertebrates>](http://purl.obolibrary.org/obo/NCBITaxon_7742) SubClassOf [Craniata <chordates>](http://purl.obolibrary.org/obo/NCBITaxon_89593) [taxslim.owl]
- [Panarthropoda](http://purl.obolibrary.org/obo/NCBITaxon_88770) SubClassOf [Ecdysozoa](http://purl.obolibrary.org/obo/NCBITaxon_1206794) [taxslim.owl]
- [Craniata <chordates>](http://purl.obolibrary.org/obo/NCBITaxon_89593) SubClassOf [Chordata](http://purl.obolibrary.org/obo/NCBITaxon_7711) [taxslim.owl]
- [heart](http://purl.obolibrary.org/obo/UBERON_0000948) SubClassOf [only in taxon](http://purl.obolibrary.org/obo/RO_0002160) some [Vertebrata <vertebrates>](http://purl.obolibrary.org/obo/NCBITaxon_7742) [uberon-base.owl]
- [cardiac muscle tissue](http://purl.obolibrary.org/obo/UBERON_0001133) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [heart](http://purl.obolibrary.org/obo/UBERON_0000948) [uberon-base.owl]
- [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Protostomia](http://purl.obolibrary.org/obo/NCBITaxon_33317) DisjointWith [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Deuterostomia](http://purl.obolibrary.org/obo/NCBITaxon_33511) [taxslim-disjoint-over-in-taxon.owl]
- [part of](http://purl.obolibrary.org/obo/BFO_0000050) SubPropertyOf: [overlaps](http://purl.obolibrary.org/obo/RO_0002131) [ro-base.owl]
- [only in taxon](http://purl.obolibrary.org/obo/RO_0002160) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162) [ro-base.owl]
- [develops from](http://purl.obolibrary.org/obo/RO_0002202) SubPropertyOf: [has developmental contribution from](http://purl.obolibrary.org/obo/RO_0002254) [uberon-base.owl]
- [overlaps](http://purl.obolibrary.org/obo/RO_0002131) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162) [uberon-base.owl]
- [has developmental contribution from](http://purl.obolibrary.org/obo/RO_0002254) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162) [ro-base.owl]

# Ontologies used: 
- uberon-base.owl (http://purl.obolibrary.org/obo/uberon/uberon-base.owl)
- cl-base.owl (http://purl.obolibrary.org/obo/cl/cl-base.owl)
- taxslim.owl (http://purl.obolibrary.org/obo/ncbitaxon/subsets/taxslim.owl)
- taxslim-disjoint-over-in-taxon.owl (http://purl.obolibrary.org/obo/ncbitaxon/subsets/taxslim-disjoint-over-in-taxon.owl)
- ro-base.owl (http://purl.obolibrary.org/obo/ro/ro-base.owl)

**Comment by gouttegd** [comment]
I (and others) have been adding some taxon restriction in several places, but I don’t recall adding one anywhere near the classes involved here…

I think the problematic bit is this one:

* [cardiac muscle tissue](http://purl.obolibrary.org/obo/UBERON_0001133) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [heart](http://purl.obolibrary.org/obo/UBERON_0000948)

That tissue should be part of [circulatory organ](http://purl.obolibrary.org/obo/UBERON_0015228), which is taxon-neutral, instead of [heart](http://purl.obolibrary.org/obo/UBERON_0000948), which is vertebrate-specific. (Though this will requires some careful checking: [cardiac muscle tissue](http://purl.obolibrary.org/obo/UBERON_0001133) is a [striated muscle tissue](http://purl.obolibrary.org/obo/UBERON_0002036) – are we sure that _all_ heart-like organs are always made of striated muscle?

In any case it does not look like this axiom was introduced recently, so I am concerned that the issue has never been flagged before. I did a complete merge of Uberon+CL+FBbt (plus the corresponding bridges) two days ago and didn’t catch anything.

**Comment by balhoff** [comment]
@gouttegd this check builds and integrates various ontologies from their source, with the aim of catching problems before release: https://github.com/INCATools/ubergraph/blob/master/ci/test-merged.sh — so it may be slightly different content from what you merged.

**Comment by gouttegd** [comment]
Thanks! That’s the kind of cross-ontology CI checks that I would like to see broadly adopted!

And right, I know why I didn’t catch anything: because I am stupid and I had not included the `taxslim-disjoint-over-in-taxon.owl` component in my own check, meaning that I was not set up to catch _any_ taxon-related problem… 🤦 

And now I have ~3,600 larval interneurons that are somehow unsatisfiable. :scream:

**Comment by balhoff** [comment]
@gouttegd thanks so much! The check is green again.
