### ISSUE TITLE
consistency check is failing during OBI build

### ISSUE THREAD

**Issue by balhoff** [INCATools/ubergraph#125]
@jamesaoverton it seems like the Ubergraph consistency check is failing while trying to build OBI, but I don't see any error output: https://github.com/INCATools/ubergraph/actions/runs/5300978907/jobs/9594900314

Do have an idea offhand what's going wrong?

**Comment by jamesaoverton** [comment]
I don't understand what's happening in that Make output. You're building an OBI base file?

**Comment by balhoff** [comment]
Yes, this is the script that's running: https://github.com/INCATools/ubergraph/blob/master/ci/test-merged.sh

**Comment by balhoff** [comment]
I think OBI was a red herring; it's the last thing in the script and the next step doesn't produce output unless there is an `explain` result. This problem resolved itself—I suspect this was actually caused by https://github.com/obophenotype/ncbitaxon/issues/76.
