### ISSUE TITLE
information content calculation is producing NaN

### ISSUE THREAD

**Issue by balhoff** [INCATools/ubergraph#132]
My guess is this is a 32-bit vs. 64-bit mixup with with Souffle.

**Comment by gaurav** [comment]
Example: https://api.triplydb.com/s/hVKIV_tKG

**Comment by balhoff** [comment]
This is now fixed. I reverted to an older docker image for the build. We can use a newer one once this is released: https://github.com/INCATools/ontology-development-kit/pull/935
