### ISSUE TITLE
Add Vertebrate Breed Ontology to Ubergraph

### ISSUE THREAD

**Issue by katiermullen** [INCATools/ubergraph#153]
Here is the link to the VBO repo: https://github.com/monarch-initiative/vertebrate-breed-ontology

Please let us know if you need any additional information! Thank you!

@sabrinatoro

**Comment by balhoff** [comment]
@katiermullen @sabrinatoro VBO should be available in Ubergraph now: https://api.triplydb.com/s/xN8sS1Vgj

**Comment by sabrinatoro** [comment]
This is great news! Thank you @balhoff

**Comment by katiermullen** [comment]
Thank you @balhoff!
