### ISSUE TITLE
Update cycle of ubergraphs?

### ISSUE THREAD

**Issue by matentzn** [INCATools/ubergraph#30]
As we get more dependent on ubergraphs, especially for QC and report queries that are too slow using Jena, we will need the information in it more and more up to date. Is there a plan to have regularly reloads of freshly updated ontologies etc?

**Comment by matentzn** [comment]
(I am talking about the endpoint, not the software)

**Comment by balhoff** [comment]
I'm setting up the Jenkins build to start every Friday morning, so that I would typically deploy every Monday. How does that sound?

**Comment by matentzn** [comment]
Weekly updates would be amazing. Once this is in place, I will build some procedures that will build a bit more dependency on Uber graph. We can talk about that in one of the next meetings.
