### ISSUE TITLE
Sparql endpoint in Readme.md

### ISSUE THREAD

**Issue by ddooley** [INCATools/ubergraph#37]
At moment that URL downloads an rdf file.  Maybe that's needed for a direct post/get API call, but do you want to provide the website URL too, the one with #sparql anchor?: https://stars-app.renci.org/ubergraph#sparql

**Comment by balhoff** [comment]
Hi @ddooley, sometime soon I will be disabling access to the Blazegraph UI, so folks will need to use the service endpoint via some other tool. I suggest YASGUI: https://api.triplydb.com/s/_26lcKdBY

**Comment by balhoff** [comment]
I'll try to add some more info to the README.

**Comment by balhoff** [comment]
The new endpoint is `https://ubergraph.apps.renci.org/sparql`; this has no web UI, just a SPARQL service.
