### ISSUE TITLE
preserve version IRIs for loaded ontologies

### ISSUE THREAD

**Issue by balhoff** [INCATools/ubergraph#39]
Right now ontologies are merged before loading. We should find a way to load all without losing all the ontology declarations. Maybe a SPARQL query would be a way to do it. It is problematic to load Blazegraph directly from the mirror directory, because the mirrored ontologies could be in any OWL format and possibly not RDF.

**Comment by matentzn** [comment]
I would still like these ontologies to be loaded into separate named graphs, and then you can just keep the ontology annos exactly as they are.. Cant you run the merge to get the inferences and then load the base files one by one?

**Comment by balhoff** [comment]
I know you asked for that in #6. One thing that has made me hesitate is just the user experience for queries with so many different graphs. Right now if you want labels you get them out of the "ontology" graph. With a graph for every ontology you would need to use the default graph for those patterns. Maybe that's fine. So far I've mostly used graphs to distinguish different inference results.

**Comment by matentzn** [comment]
I fear to say it, but what about loading both a merged an all the named graphs together? Would this trouble blazegraph?

**Comment by balhoff** [comment]
I think it would be fine, and maybe I would deprecate the ontology graph for a little while and then drop it. I also want to drop the "closure" graph. I'll need to rewrite the mirror stuff to be more like GO/ODK (`curl` instead of `robot mirror`).

**Comment by matentzn** [comment]
You could also pretty much use ODK now that it supports base management.. But don't let that add to your workload.

**Comment by balhoff** [comment]
Should be made possible by #40.
