### ISSUE TITLE
add more ontologies?

### ISSUE THREAD

**Issue by sierra-moxon** [INCATools/ubergraph#54]
Name| Prefix | purl
-- | -- | --
Ascomycete phenotype ontology | APO |http://purl.obolibrary.org/obo/APO.owl
Biological Spatial Ontology | bspo | http://purl.obolibrary.org/obo/bspo.owl
Brenda Tissue Ontology | bto | http://purl.obolibrary.org/obo/bto.owl
C. elegans (nematode) Life Stage | wbls | http://purl.obolibrary.org/obo/wbls.owl
C. elegans Anatomy | wbbt | http://purl.obolibrary.org/obo/wbbt.owl
C. elegans Phenotype | wbphenotype | http://purl.obolibrary.org/obo/wbphenotype.owl
Drosophila Development | fbdv | http://purl.obolibrary.org/obo/fbdv.ow
Drosophila Phenotype Ontology | dpo | http://purl.obolibrary.org/obo/dpo.owl
FlyBase Controlled Vocabulary | fbcv | http://purl.obolibrary.org/obo/fbcv.owl
Measurement Method Ontology | MMO | http://purl.obolibrary.org/obo/MMO.owl
Molecular interactions | MI | http://purl.obolibrary.org/obo/MI.owl
Mouse adult gross anatomy | ma | http://purl.obolibrary.org/obo/ma.owlo
Mouse Developmental Stage Ontology | mmusdv | http://purl.obolibrary.org/obo/mmusdv.owl
Mouse gross anatomy and development, timed | emapa | http://purl.obolibrary.org/obo/emapa.owl
Sequence Types and Features | SO | http://purl.obolibrary.org/obo/SO.owl
Zebrafish Anatomy | ZFA | http://purl.obolibrary.org/obo/ZFA.owl
Zebrafish Developmental Stages | ZFS | http://purl.obolibrary.org/obo/ZFS.owl

**Comment by balhoff** [comment]
For my notes: ZFS terms are included in zfa-base.owl.
