### ISSUE TITLE
Remove EFO (or replace with simplified version if available)

### ISSUE THREAD

**Issue by dosumis** [INCATools/ubergraph#62]
EFO-base is injecting axioms that cause some serious reasoning errors.  See https://github.com/EBISPOT/efo/issues/1582 for an example.   The very large amount of inconsistency that comes from merging EFO, Uberon and CL (I just tested this locally) is also a bad sign - possibly indicating other axiom injection.

I think EFO needs to be removed from UberGraph or replaced with a -simple version (only EFO classes + subClassOf and simple existential restrictions).

**Comment by balhoff** [comment]
@cbizon — for Data Translator purposes, do you need the relation-graph edges for EFO? Or would it make sense to just have EFO loaded into the ontologies graph, without including it in the OWL reasoning done on the whole group?
