### ISSUE TITLE
Add GRLC query for an API that retrieves "relacedBy" annotations

### ISSUE THREAD

**Issue by matentzn** [INCATools/ubergraph#77]
We need a GRLC query for an API that retrieves "relacedBy" annotations for terms to provide to our stakeholders. For now the API should, ideally, be resilient to:

- using alt_id instead of replacedBy
- using CURIE strings instead of IRI

But ideally, we should push for all our ontologies to fix these inconsistent representations at source.

**Comment by anitacaron** [comment]
Create two queries:
1. From one ontology, get the list of all replaced by terms
2. From one term get the replaced by a term
