### ISSUE TITLE
TSV version of the graph

### ISSUE THREAD

**Issue by LucaCappelletti94** [INCATools/ubergraph#80]
Hello,

Is there a TSV version of the graph available somewhere?

Thanks,
Luca

**Comment by LucaCappelletti94** [comment]
Ok! Do you need some help with the conversion? Maybe with the quality control of the result?

**Comment by LucaCappelletti94** [comment]
Hello @matentzn ! Yes, a KGX dump would work.

**Comment by balhoff** [comment]
> TSV version of the graph - why isn't this simply a KGX dump?

That would be fine, we just need code in the Makefile to create the KGX dump (I started this but it's not used), and decide where to host it. Do you think I should post Ubergraph versions to Zenodo?

**Comment by balhoff** [comment]
These downloads are now available.
