### ISSUE TITLE
New incoherency

### ISSUE THREAD

**Issue by balhoff** [INCATools/ubergraph#82]
https://github.com/INCATools/ubergraph/runs/7849044206?check_suite_focus=true

## [sporocarp development involved in asexual reproduction](http://purl.obolibrary.org/obo/GO_0000905) SubClassOf [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [sporocarp development involved in asexual reproduction](http://purl.obolibrary.org/obo/GO_0000905) EquivalentTo [sporocarp development](http://purl.obolibrary.org/obo/GO_0030584) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [asexual reproduction](http://purl.obolibrary.org/obo/GO_0019954))
    - [sporocarp development](http://purl.obolibrary.org/obo/GO_0030584) SubClassOf [reproductive fruiting body development](http://purl.obolibrary.org/obo/GO_0030582)
      - [reproductive fruiting body development](http://purl.obolibrary.org/obo/GO_0030582) SubClassOf [spore-bearing structure development](http://purl.obolibrary.org/obo/GO_0075259)
        - [spore-bearing structure development](http://purl.obolibrary.org/obo/GO_0075259) SubClassOf [reproductive structure development](http://purl.obolibrary.org/obo/GO_0048608)
          - [reproductive structure development](http://purl.obolibrary.org/obo/GO_0048608) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [reproductive system development](http://purl.obolibrary.org/obo/GO_0061458)
            - [reproductive system development](http://purl.obolibrary.org/obo/GO_0061458) EquivalentTo [anatomical structure development](http://purl.obolibrary.org/obo/GO_0048856) and ([results in development of](http://purl.obolibrary.org/obo/RO_0002296) some [reproductive system](http://purl.obolibrary.org/obo/UBERON_0000990))
              - [reproductive system](http://purl.obolibrary.org/obo/UBERON_0000990) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [genitourinary system](http://purl.obolibrary.org/obo/UBERON_0004122)
                - [genitourinary system](http://purl.obolibrary.org/obo/UBERON_0004122) EquivalentTo [anatomical system](http://purl.obolibrary.org/obo/UBERON_0000467) and ([has part](http://purl.obolibrary.org/obo/BFO_0000051) some [reproductive system](http://purl.obolibrary.org/obo/UBERON_0000990)) and ([has part](http://purl.obolibrary.org/obo/BFO_0000051) some [renal system](http://purl.obolibrary.org/obo/UBERON_0001008))
                  - [renal system](http://purl.obolibrary.org/obo/UBERON_0001008) SubClassOf [only in taxon](http://purl.obolibrary.org/obo/RO_0002160) some [Eumetazoa](http://purl.obolibrary.org/obo/NCBITaxon_6072)
                    - [only in taxon](http://purl.obolibrary.org/obo/RO_0002160) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
                    - [Eumetazoa](http://purl.obolibrary.org/obo/NCBITaxon_6072) SubClassOf [Metazoa](http://purl.obolibrary.org/obo/NCBITaxon_33208)
              - [results in development of](http://purl.obolibrary.org/obo/RO_0002296) SubPropertyOf: [results in developmental progression of](http://purl.obolibrary.org/obo/RO_0002295)
    - [part of](http://purl.obolibrary.org/obo/BFO_0000050) SubPropertyOf: [overlaps](http://purl.obolibrary.org/obo/RO_0002131)
  - [overlaps](http://purl.obolibrary.org/obo/RO_0002131) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
  - [spore-bearing structure development](http://purl.obolibrary.org/obo/GO_0075259) DisjointWith [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Metazoa](http://purl.obolibrary.org/obo/NCBITaxon_33208)
  - [results in developmental progression of](http://purl.obolibrary.org/obo/RO_0002295) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
  - [has part](http://purl.obolibrary.org/obo/BFO_0000051) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)

# Axiom Impact 
## Axioms used 1 times
- [sporocarp development involved in asexual reproduction](http://purl.obolibrary.org/obo/GO_0000905) EquivalentTo [sporocarp development](http://purl.obolibrary.org/obo/GO_0030584) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [asexual reproduction](http://purl.obolibrary.org/obo/GO_0019954)) [go-base.owl]
- [reproductive system development](http://purl.obolibrary.org/obo/GO_0061458) EquivalentTo [anatomical structure development](http://purl.obolibrary.org/obo/GO_0048856) and ([results in development of](http://purl.obolibrary.org/obo/RO_0002296) some [reproductive system](http://purl.obolibrary.org/obo/UBERON_0000990)) [go-base.owl]
- [genitourinary system](http://purl.obolibrary.org/obo/UBERON_0004122) EquivalentTo [anatomical system](http://purl.obolibrary.org/obo/UBERON_0000467) and ([has part](http://purl.obolibrary.org/obo/BFO_0000051) some [reproductive system](http://purl.obolibrary.org/obo/UBERON_0000990)) and ([has part](http://purl.obolibrary.org/obo/BFO_0000051) some [renal system](http://purl.obolibrary.org/obo/UBERON_0001008)) [uberon-base.owl]
- [reproductive fruiting body development](http://purl.obolibrary.org/obo/GO_0030582) SubClassOf [spore-bearing structure development](http://purl.obolibrary.org/obo/GO_0075259) [go-base.owl]
- [sporocarp development](http://purl.obolibrary.org/obo/GO_0030584) SubClassOf [reproductive fruiting body development](http://purl.obolibrary.org/obo/GO_0030582) [go-base.owl]
- [reproductive structure development](http://purl.obolibrary.org/obo/GO_0048608) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [reproductive system development](http://purl.obolibrary.org/obo/GO_0061458) [go-base.owl]
- [spore-bearing structure development](http://purl.obolibrary.org/obo/GO_0075259) SubClassOf [reproductive structure development](http://purl.obolibrary.org/obo/GO_0048608) [go-base.owl]
- [Eumetazoa](http://purl.obolibrary.org/obo/NCBITaxon_6072) SubClassOf [Metazoa](http://purl.obolibrary.org/obo/NCBITaxon_33208) [taxslim.owl]
- [reproductive system](http://purl.obolibrary.org/obo/UBERON_0000990) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [genitourinary system](http://purl.obolibrary.org/obo/UBERON_0004122) [uberon-base.owl]
- [renal system](http://purl.obolibrary.org/obo/UBERON_0001008) SubClassOf [only in taxon](http://purl.obolibrary.org/obo/RO_0002160) some [Eumetazoa](http://purl.obolibrary.org/obo/NCBITaxon_6072) [uberon-base.owl]
- [spore-bearing structure development](http://purl.obolibrary.org/obo/GO_0075259) DisjointWith [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Metazoa](http://purl.obolibrary.org/obo/NCBITaxon_33208) [go-base.owl]
- [part of](http://purl.obolibrary.org/obo/BFO_0000050) SubPropertyOf: [overlaps](http://purl.obolibrary.org/obo/RO_0002131) [ro-base.owl]
- [only in taxon](http://purl.obolibrary.org/obo/RO_0002160) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162) [ro-base.owl]
- [results in development of](http://purl.obolibrary.org/obo/RO_0002296) SubPropertyOf: [results in developmental progression of](http://purl.obolibrary.org/obo/RO_0002295) [ro-base.owl]
- [has part](http://purl.obolibrary.org/obo/BFO_0000051) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162) [ro-base.owl]
- [overlaps](http://purl.obolibrary.org/obo/RO_0002131) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162) [uberon-base.owl]
- [results in developmental progression of](http://purl.obolibrary.org/obo/RO_0002295) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162) [ro-base.owl]

# Ontologies used: 
- uberon-base.owl (http://purl.obolibrary.org/obo/uberon/uberon-base.owl)
- taxslim.owl (http://purl.obolibrary.org/obo/ncbitaxon/subsets/taxslim.owl)
- ro-base.owl (http://purl.obolibrary.org/obo/ro/ro-base.owl)
- go-base.owl (http://purl.obolibrary.org/obo/go/go-base.owl)

**Comment by balhoff** [comment]
@matentzn @shawntanzk @anitacaron we need to check the latest commits and find what went wrong. :-)

**Comment by shawntanzk** [comment]
This is the offending PR https://github.com/obophenotype/uberon/commit/40e47c686350786a411775cd2c1340652b6566e1

**Comment by balhoff** [comment]
Fixed by https://github.com/obophenotype/uberon/pull/2612
