### ISSUE TITLE
change IC score to count all incoming relations

### ISSUE THREAD

**Issue by balhoff** [INCATools/ubergraph#94]
Right now the precomputed information content score is based on incoming `subClassOf` and `part_of` relations: https://github.com/INCATools/ubergraph/blob/b6c07bd169aaa22fdaf376fbe2ca40cbb9ba44fb/ic.dl#L18-L19

We are thinking of changing this to reflect any relation in the redundant graph. This way any term that is frequently referenced in axioms would get a lower IC score.

@dosumis is your group using this number for anything? Trying to see if anyone outside of Data Translator (@cbizon) would notice this.

**Comment by balhoff** [comment]
For example, right now [hydron](http://purl.obolibrary.org/obo/CHEBI_15378) has reference count `5`. But in the updated counting it would be `136`, giving a much lower IC.

**Comment by dosumis** [comment]
We've been using it experimentally in CAP, but I don't think it's turned out to be that useful for what we were trying to achieve.  @ubyndr - do you have any details to add?

**Comment by ubyndr** [comment]
We tried to utilize this to propose a grouping for their anatomical structures, but they weren't so eager to use this analysis.
