### ISSUE TITLE
Add OBA to Ubergraph

### ISSUE THREAD

**Issue by matentzn** [INCATools/ubergraph#96]
Plus the materialised links between OBA and phenotype ontologies.

**Comment by matentzn** [comment]
Do you object to this @balhoff

**Comment by balhoff** [comment]
Not at all.

**Comment by balhoff** [comment]
@matentzn which links are you referring to? Will that come from reasoning or do we need to load a file?

**Comment by matentzn** [comment]
Basically, in order to get all the OBA-HPO links, you need to materialise has-part (BFO:0000051). That will make sure that HPO:1 subclassOf BFO:0000051 some OBA:1!

**Comment by balhoff** [comment]
Okay, that will happen automatically!

**Comment by balhoff** [comment]
@matentzn oh it won't work, because all the HP logical definitions require `'has modifier' some abnormal`.

**Comment by matentzn** [comment]
😱  Oh oh.. I must be making some fundamental mistake.. shoooooot.. This is what I was thinking:

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/7070631/201924001-0c2c2eb2-c801-45ba-afce-4c3959f98b8b.png">

Is this not correct? This does not bode well for my vision :D

**Comment by balhoff** [comment]
Aargh, you are totally right, I wasn't thinking straight.

**Comment by balhoff** [comment]
Yes check it out! https://api.triplydb.com/s/kBG-9b08U

**Comment by matentzn** [comment]
THIS IS TOO AMAZING!
